[tool.briefcase.app]
formal_name = "MyWeatherApp"
app_name = "myweatherapp"
bundle = "weather.app"
project_name = "MyWeatherApp"
description = "This is a weather app"
author = "Ali Raza"
license = "MIT"
