[tool.briefcase.app]
formal_name = "MyWeatherApp"
app_name = "myweatherapp"
bundle = "com.example"
project_name = "MyWeatherApp"
description = "This is a weather app"
author = "John Doe"
license = "MIT"