name: Install Dependencies

on:
  workflow_run:
    workflows: ["Build Python App with Buildozer"]
    types:
      - completed

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        sudo apt-get install -y python3-pip libssl-dev libffi-dev python3-dev
        pip install buildozer cython

        # Add commands to install any additional dependencies your app requires

        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;35.0.0-rc1"

        expect -c 'spawn $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses; expect "y/n" { send "y\r"; exp_continue }'
