name: Build and Deploy Android App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required tools
        uses: mox/setup-android-sdk@v1
        with:
          sdk_root: <path/to/sdk>
          ndk_version: <ndk_version> # Optional
          packages:
            build-tools;35.0.0-rc1 # Replace with your version if needed

      - name: Check build-tools folder
        run: |
          if [ ! -d "$ANDROID_HOME/build-tools" ]; then
            echo "Build-tools folder not found. Please install required tools."
            exit 1
          fi

      - name: Install Buildozer
        run: pip install buildozer

      - name: Update buildozer.spec
        run: |
          echo 'android.sdk_tools_version = 35.0.0-rc1' >> buildozer.spec 

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}