name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev build-essential
        pip install buildozer cython

    - name: Set up Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget -q "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip" -O android-sdk-tools.zip
        unzip -q android-sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin

    - name: Update PATH
      run: echo "export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin" >> $HOME/.bashrc

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses

    - name: Build Android app with Buildozer
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-artifact
        path: bin/*.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download APK artifact
      uses: actions/download-artifact@v2
      with:
        name: app-artifact
        path: output/android/  

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v3
      with:
        files: |
          output/android/*.apk
        token: ${{ secrets.GH_TOKEN }}
        body: |
          Release notes go here. You can customize this section.
        draft: false
        prerelease: false
