name: Build Python App with Buildozer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install JDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk

    - name: Install Android SDK and NDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
        unzip commandlinetools-linux-7302050_latest.zip -d $HOME/android-sdk
        echo "y" | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;30.0.3" "platforms;android-30" "ndk;21.3.6528147"
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=\$PATH:\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools" >> $GITHUB_ENV

    - name: Install Buildozer and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip libssl-dev libffi-dev python3-dev
        pip install buildozer cython

    - name: Configure Buildozer
      run: |
        # Example of creating a basic buildozer.spec. Adjust according to your needs.
        buildozer init
        sed -i 's/log_level = 2/log_level = 1/' buildozer.spec
        sed -i 's/# android.ndk_path =/android.ndk_path = $HOME\/android-sdk\/ndk\/21.3.6528147/' buildozer.spec

    - name: Build the App
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: APK
        path: bin/*.apk
