# main.yml

name: Build Python App with Buildozer

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        sudo apt-get install -y python3-pip libssl-dev libffi-dev python3-dev
        pip install buildozer cython

        # Add commands to install any additional dependencies your app requires

        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;35.0.0-rc1"

        expect -c 'spawn $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses; expect "y/n" { send "y\r"; exp_continue }'

  build:
    runs-on: ubuntu-latest

    needs: install_dependencies  # Ensure dependencies job is completed before starting this job

    env:
      ANDROID_SDK_ROOT: $HOME/android-sdk
      ANDROID_NDK_PATH: $ANDROID_SDK_ROOT/ndk/21.3.6528147

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Android SDK and NDK
      run: |
        mkdir -p $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
        unzip commandlinetools-linux-7302050_latest.zip -d $HOME/android-sdk
        echo y | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "build-tools;30.0.3" "platforms;android-30" "ndk;21.3.6528147"
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=\$PATH:\$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:\$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_ENV
      
    - name: Configure Buildozer
      run: |
        buildozer init
        sed -i 's/log_level = 2/log_level = 1/' buildozer.spec
        sed -i 's/# android.ndk_path =/android.ndk_path = $HOME\/android-sdk\/ndk\/21.3.6528147/' buildozer.spec
        sed -i 's/android.api = 21/android.api = 30/' buildozer.spec

    - name: Build the App
      run: |
        echo y | buildozer -v android debug

    - name: Clean Up
      run: |
        rm -rf .buildozer

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: APK
        path: bin/*.apk
