name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # or any version that is compatible with Buildozer

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev  # Install Python development headers
        pip install buildozer

    - name: Build Android app with Buildozer
      run: |
        cd ${{ github.workspace }}
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-artifact
        path: bin/*.apk  # Adjust the path to your built APK file

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download APK artifact
      uses: actions/download-artifact@v3
      with:
        name: app-artifact
        path: output/android/  # Adjust the path to match the upload path

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v3
      with:
        files: |
          output/android/*.apk
        token: ${{ secrets.GH_TOKEN }}
        body: |
          Release notes go here. You can customize this section.
        draft: false
        prerelease: false
