name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the public Linux runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12  # Use the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install briefcase
        pip install kivy
        pip install requests

 #   - name: Provide formal name for the Briefcase app
 #     run: |
#        echo -e "MyWeatherApp\nmyweatherapp\ncom.app\nMyWeatherApp\nThis is a weather app\nAli Raza\ngoldliak47@gmail.com\nhttps://app.com/myweatherapp\n4\n1" | briefcase new

    - name: Build Android app
      run: |
        echo pyproject.toml | briefcase dev

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-artifact
        path: output/android/  # Adjust the path to your built artifacts

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download APK artifact
      uses: actions/download-artifact@v3
      with:
        name: app-artifact
        path: output/android/  # Adjust the path to match the upload path

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v3
      with:
        files: |
          output/android/*.apk
        token: ${{ secrets.GH_TOKEN }}
        body: |
          Release notes go here. You can customize this section.
        draft: false
        prerelease: false
